services:
  - type: web
    name: moneytalks
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn run:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2